apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 903150814166.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2-mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password123"
    - name: MYSQL_DATABASE
      value: "employees"
  imagePullSecrets:
    - name: ecr-secret
